version: "3.9"

services:
  # === Storages ===

  data-storage:
    image: postgres:alpine3.18
    container_name: trello_storage
    restart: always
    environment:
      POSTGRES_DB: "trello_db"
      POSTGRES_USER: "slava"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./scripts/migrations/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/migrations/init_data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5432:5432"
    networks:
      - trello-network
    deploy:
      restart_policy:
        condition: on-failure

  sessions-storage:
    image: redis:alpine3.18
    container_name: trello_sessions
    restart: always
    environment:
      REDIS_PASSWORD: "1234"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    networks:
      - trello-network
    deploy:
      restart_policy:
        condition: on-failure

  # === Services ===

  api:
    image: trello_api
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: trello_api
    ports:
      - "8000:8000"
    depends_on:
      - data-storage
      - sessions-storage
    volumes:
      - ./cmd/api/logs:/logs
      - ./configs/api.yaml:/configs/api.yaml
      - ./.aws:/root/.aws
    networks:
      - trello-network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  trello-network:
    driver: bridge
    name: trello_network
