# Server
NAME: mirror
PORT: 8003

# Postgres
PG_HOST: data-storage-rep
PG_PORT: 5433
PG_DB: trello_db
PG_USER: moderator
PG_PASSWORD: 2222
PG_SSL_MODE: disable

# Redis
REDIS_HOST: sessions-storage
REDIS_PORT: 6379
REDIS_PASSWORD: 1234

# Validation
MIN_USERNAME_LEN: 4
MAX_USERNAME_LEN: 30
