basePath: /api/v1
definitions:
  http.JSONError:
    properties:
      error:
        type: string
    type: object
  http.signInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  http.signInResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  http.signUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  http.signUpResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  internal_users_delivery_http.getResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  internal_users_delivery_http.partialUpdateRequest:
    properties:
      email:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  internal_workspaces_delivery_http.createRequest:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  internal_workspaces_delivery_http.createResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  internal_workspaces_delivery_http.getResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  internal_workspaces_delivery_http.listResponse:
    properties:
      workspaces:
        items:
          $ref: '#/definitions/models.Workspace'
        type: array
    type: object
  internal_workspaces_delivery_http.partialUpdateRequest:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  models.Workspace:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
host: localhost
info:
  contact:
    email: my-trello-support@yandex.ru
    name: MyTrello API Support
    url: http://127.0.0.1/support
  description: MyTrello API documentation.
  termsOfService: http://127.0.0.1/terms
  title: MyTrello API
  version: "1.0"
paths:
  /auth/logout:
    delete:
      description: Logs out and deletes the authentication cookie.
      produces:
      - application/json
      responses:
        "204":
          description: Successfully logged out.
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Logs out and deletes the authentication cookie.
      tags:
      - auth
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Logs in and returns the authentication cookie
      parameters:
      - description: Successfully authenticated.
        in: body
        name: signInParams
        required: true
        schema:
          $ref: '#/definitions/http.signInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: successfully auth
          schema:
            $ref: '#/definitions/http.signInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Logs in and returns the authentication cookie
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Creates new user and returns authentication cookie.
      parameters:
      - description: Sign up params.
        in: body
        name: signUpParams
        required: true
        schema:
          $ref: '#/definitions/http.signUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user.
          schema:
            $ref: '#/definitions/http.signUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Creates new user and returns authentication cookie.
      tags:
      - auth
  /users/{id}:
    get:
      description: Returns user with specified id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/internal_users_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Returns user with specified id
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Partial update of user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data to update
        in: body
        name: UserUpdateData
        required: true
        schema:
          $ref: '#/definitions/internal_users_delivery_http.partialUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated user data
          schema:
            $ref: '#/definitions/internal_users_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Partial update of user
      tags:
      - users
  /users/{id}/avatar:
    put:
      consumes:
      - multipart/form-data
      description: Update user avatar
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Avatar
        in: body
        name: avatar
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: Updated user data
          schema:
            $ref: '#/definitions/internal_users_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Update user avatar
      tags:
      - users
  /workspaces:
    get:
      description: Returns all workspaces with boards of current user
      produces:
      - application/json
      responses:
        "200":
          description: Workspaces data
          schema:
            $ref: '#/definitions/internal_workspaces_delivery_http.listResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Returns all workspaces with boards of current user
      tags:
      - workspaces
    post:
      consumes:
      - application/json
      description: Create a new workspace
      parameters:
      - description: Workspace create data
        in: body
        name: WorkspaceCreateData
        required: true
        schema:
          $ref: '#/definitions/internal_workspaces_delivery_http.createRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Created workspace data.
          schema:
            $ref: '#/definitions/internal_workspaces_delivery_http.createResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Create a new workspace
      tags:
      - workspaces
  /workspaces/{id}:
    delete:
      description: Delete workspace by id
      parameters:
      - description: Workspace ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Workspace deleted successfully
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Delete workspace by id
      tags:
      - workspaces
    get:
      description: Returns workspace by id
      parameters:
      - description: Workspace ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Workspace data
          schema:
            $ref: '#/definitions/internal_workspaces_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Returns workspace by id
      tags:
      - workspaces
    patch:
      consumes:
      - application/json
      description: Partial update of workspace
      parameters:
      - description: Workspace ID
        in: path
        name: id
        required: true
        type: integer
      - description: Workspace data to update
        in: body
        name: WorkspaceUpdateData
        required: true
        schema:
          $ref: '#/definitions/internal_workspaces_delivery_http.partialUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated workspace data.
          schema:
            $ref: '#/definitions/internal_workspaces_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Partial update of workspace
      tags:
      - workspaces
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
