name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Up containers
        run: make run-test-containers

      - name: Run unit tests
        run: docker compose exec test make unit-test

      - name: Run integration tests
        run: docker compose exec test make integration-test

      - name: Run end-to-end tests
        run: docker compose exec test make e2e-test
