name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Up test containers
        run: make test-up

      - name: Run unit tests
        run: docker compose exec test make unit-test
        if: ${{ success() }}

      - name: Run integration tests
        run: docker compose exec test make integration-test
        if: ${{ success() }}

      - name: Run end-to-end tests
        run: docker compose exec test make e2e-test
        if: ${{ success() }}

      - name: Stop test containers
        run: make test-stop
